"""newer updates

Revision ID: 1de6932a966a
Revises: 2cad7afc8550
Create Date: 2023-09-20 14:19:01.005265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de6932a966a'
down_revision = '2cad7afc8550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primeiro_nome', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sobrenome', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('celular', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))
        batch_op.drop_column('dieta')
        batch_op.drop_column('alergias')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alergias', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dieta', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('estado')
        batch_op.drop_column('pais')
        batch_op.drop_column('cep')
        batch_op.drop_column('endereco')
        batch_op.drop_column('celular')
        batch_op.drop_column('sobrenome')
        batch_op.drop_column('primeiro_nome')

    # ### end Alembic commands ###
