"""fixing adding tabless

Revision ID: 222bff6bde45
Revises: 423c6fa09c1d
Create Date: 2023-10-19 18:03:58.376955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222bff6bde45'
down_revision = '423c6fa09c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alimento')
    op.drop_table('dieta')
    op.drop_table('refeicao')
    op.drop_table('refeicao_alimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refeicao_alimento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('refeicao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dieta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimento.id'], name='refeicao_alimento_alimento_id_fkey'),
    sa.ForeignKeyConstraint(['dieta_id'], ['dieta.id'], name='refeicao_alimento_dieta_id_fkey'),
    sa.ForeignKeyConstraint(['refeicao_id'], ['refeicao.id'], name='refeicao_alimento_refeicao_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refeicao_alimento_pkey')
    )
    op.create_table('refeicao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='refeicao_pkey')
    )
    op.create_table('dieta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='dieta_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dieta_pkey')
    )
    op.create_table('alimento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('calorias', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='alimento_pkey')
    )
    # ### end Alembic commands ###
