"""adjusting

Revision ID: 2ac767a89267
Revises: 32a8bf28f276
Create Date: 2023-10-12 17:17:41.373974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac767a89267'
down_revision = '32a8bf28f276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False))
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.drop_constraint('exercicio_treino_id_fkey', type_='foreignkey')
        batch_op.drop_column('treino_id')

    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.alter_column('objetivo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.alter_column('objetivo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('exercicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treino_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('exercicio_treino_id_fkey', 'treino', ['treino_id'], ['id'])
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
