"""adjusting new migrationnnn

Revision ID: 32a8bf28f276
Revises: 330509e8d2e0
Create Date: 2023-10-12 16:23:58.199496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a8bf28f276'
down_revision = '330509e8d2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genero', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nivel_atividade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('objetivo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('tipo_atividade', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dashboard_user_pkey')
    )
    # ### end Alembic commands ###
