"""adjusting new migration

Revision ID: 330509e8d2e0
Revises: b54d6d79925f
Create Date: 2023-10-12 16:22:42.110256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '330509e8d2e0'
down_revision = 'b54d6d79925f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dieta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('peso_atual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nivel_atividade_fisica', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('objetivo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('condicoes_medicas', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preferencias_alimentares', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('estado_saude_geral', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('dieta_usuario_id_fkey', type_='foreignkey')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('nome')
        batch_op.drop_column('almoco')
        batch_op.drop_column('cafe_manha')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('lanche_manha')
        batch_op.drop_column('janta')
        batch_op.drop_column('cafe_tarde')
        batch_op.drop_column('ceia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dieta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ceia', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cafe_tarde', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('janta', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lanche_manha', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cafe_manha', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('almoco', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('dieta_usuario_id_fkey', 'dashboard_user', ['usuario_id'], ['id'])
        batch_op.drop_column('estado_saude_geral')
        batch_op.drop_column('preferencias_alimentares')
        batch_op.drop_column('condicoes_medicas')
        batch_op.drop_column('objetivo')
        batch_op.drop_column('nivel_atividade_fisica')
        batch_op.drop_column('altura')
        batch_op.drop_column('peso_atual')
        batch_op.drop_column('sexo')
        batch_op.drop_column('idade')

    # ### end Alembic commands ###
