"""fixing db

Revision ID: 33779137ed10
Revises: 2ac767a89267
Create Date: 2023-10-19 17:42:27.886829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33779137ed10'
down_revision = '2ac767a89267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dieta')
    op.drop_table('treino_exercicio')
    op.drop_table('treino_usuario')
    op.drop_table('treino')
    op.drop_table('exercicio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('exercicio_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='exercicio_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('treino',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('treino_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('objetivo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duracao', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dia_semana', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='treino_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('treino_usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('treino_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gerado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], name='treino_usuario_treino_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='treino_usuario_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='treino_usuario_pkey')
    )
    op.create_table('treino_exercicio',
    sa.Column('treino_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercicio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id'], name='treino_exercicio_exercicio_id_fkey'),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], name='treino_exercicio_treino_id_fkey')
    )
    op.create_table('dieta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('peso_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('altura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nivel_atividade_fisica', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('objetivo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('condicoes_medicas', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('preferencias_alimentares', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('estado_saude_geral', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dieta_pkey')
    )
    # ### end Alembic commands ###
