"""changing tables

Revision ID: 39dcfa301d6a
Revises: 5caf6adfddbd
Create Date: 2023-10-02 18:43:02.965321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dcfa301d6a'
down_revision = '5caf6adfddbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refeicao', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.drop_column('refeicao')

    # ### end Alembic commands ###
