"""adding tabless

Revision ID: 423c6fa09c1d
Revises: 33779137ed10
Create Date: 2023-10-19 18:02:49.351048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423c6fa09c1d'
down_revision = '33779137ed10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refeicao_alimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dieta_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'dieta', ['dieta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refeicao_alimento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dieta_id')

    # ### end Alembic commands ###
