"""New diet table

Revision ID: 4d99dc740109
Revises: d57b5ce5f29d
Create Date: 2023-10-07 18:33:26.778279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d99dc740109'
down_revision = 'd57b5ce5f29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dieta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('tmb', sa.Float(), nullable=False),
    sa.Column('nivel_atividade', sa.String(length=20), nullable=False),
    sa.Column('objetivo', sa.String(length=10), nullable=False),
    sa.Column('tipo_atividade', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dieta')
    # ### end Alembic commands ###
