"""New table for receipts

Revision ID: 5ddf9bea6599
Revises: 0a8644772adf
Create Date: 2023-10-02 18:31:03.816319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ddf9bea6599'
down_revision = '0a8644772adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refeicao', sa.String(length=20), nullable=False))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('refeicao')

    # ### end Alembic commands ###
