"""New row of receipe table

Revision ID: 855228c2ea41
Revises: 39dcfa301d6a
Create Date: 2023-10-02 20:28:32.968722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855228c2ea41'
down_revision = '39dcfa301d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
