"""testing

Revision ID: bc527bfc5897
Revises: bef2fbabd465
Create Date: 2023-10-03 08:54:38.751708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc527bfc5897'
down_revision = 'bef2fbabd465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredientes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.drop_column('ingredientes')

    # ### end Alembic commands ###
