"""New table for receiptss

Revision ID: d93f98d258c9
Revises: 2c73409460e4
Create Date: 2023-10-02 18:35:54.553439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd93f98d258c9'
down_revision = '2c73409460e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('refeicao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refeicao', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
