"""newer updates

Revision ID: 4d5dc3580b54
Revises: 1de6932a966a
Create Date: 2023-09-20 14:27:52.434577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5dc3580b54'
down_revision = '1de6932a966a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.drop_column('pais')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
