name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  FlexiSonarCloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      # Adicione os passos para instalar dependências e executar testes aqui
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Adicione os passos para coletar relatórios de cobertura aqui
      - name: Collect coverage reports
        run: |
          pip install -r requirements.txt  # Instalação de dependências, se necessário
          pip install coverage  # Instala a biblioteca de cobertura
          coverage run -m pytest tests/test_routes.py  # Executa testes e gera relatório de cobertura
          coverage xml -o coverage-reports/coverage.xml  # Gera um relatório XML para o SonarCloud

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: eb860400e9b8ae8ea7a170ef80d32d234c9ad825
